version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=squiz  # Add this line to create the `squiz` database
    ports:
      - '5432:5432'
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist PostgreSQL data

  app:
    image: squiz-app-test
    environment:
      - DB_URL=jdbc:postgresql://db:5432/squiz  # Use Spring-specific environment variable
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data:  # Define the volume for PostgreSQL data persistence
    driver: local